[package]
name = "pgline"
version = "0.1.3"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
crossterm = "0.29.0"
futures-util = "0.3.34"
nu-ansi-term = "0.50.3"
rand = "0.10.3"
reedline = "0.51.0"
rpassword = "7.5.4"
rustls-tokio-postgres = { version = "0.5.1", features = ["platform-verifier"] }
shlex = "2.0.1"
tabled = { version = "0.22.0", default-features = false, features = ["std"] }
tempfile = "3.27.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "time",
] }
tokio-postgres = "0.7.18"
whoami = "2.1.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"
